export const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  SEND_FORGOT_MAIL_REQUEST: 'SEND_FORGOT_MAIL_REQUEST',
  SEND_FORGOT_MAIL_SUCCESS: 'SEND_FORGOT_MAIL_SUCCESS',
  SEND_FORGOT_MAIL_FAILURE: 'SEND_FORGOT_MAIL_FAILURE',
  SEND_CHANGE_PASS_REQUEST: 'SEND_CHANGE_PASS_REQUEST',
  SEND_CHANGE_PASS_SUCCESS: 'SEND_CHANGE_PASS_SUCCESS',
  SEND_CHANGE_PASS_FAILURE: 'SEND_CHANGE_PASS_FAILURE',
  RESET_ALL_FORGOT: 'RESET_ALL_FORGOT',
};
export default actionTypes;
