export const actionTypes = {
  IS_LOADING_ENABLE_REQUEST: 'IS_LOADING_ENABLE_REQUEST',
  IS_LOADING_ENABLE_SUCCESS: 'IS_LOADING_ENABLE_SUCCESS',
  IS_LOADING_DISABLE_REQUEST: 'IS_LOADING_DISABLE_REQUEST',
  IS_LOADING_DISABLE_SUCCESS: 'IS_LOADING_DISABLE_SUCCESS',
  GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',
  GET_TIMEZONE_REQUEST: 'GET_TIMEZONE_REQUEST',
  GET_TIMEZONE_SUCCESS: 'GET_TIMEZONE_SUCCESS',
  GET_TIMEZONE_FAILURE: 'GET_TIMEZONE_FAILURE',
  IS_COMPLETE_GET_COUNTRIES: 'IS_COMPLETE_GET_COUNTRIES',
  IS_COMPLETE_GET_TIMEZONE: 'IS_COMPLETE_GET_TIMEZONE',
  AUTHENTICATION_401: 'AUTHENTICATION_401',
  RESET_COMMON: 'RESET_COMMON',
};
export default actionTypes;
